### ISSUE TITLE
Settings Restructure

### ISSUE THREAD

**Issue by neomonkeus** [niftools/nifskope#13]
Note:  This issue as outlined is outdated and Settings was restructured in a different way. 
#### Proposed Settings Outline
- Settings (Top-level, visible on Menu Bar)  
  - Game Locations / Install Paths  
  - Render  
  - Export/Import  
  - Region / Language
  - Startup Defaults (NIF versions)
#### Task List
- [ ] Relocate "Settings" submenu out from under "Render" category to top-level menu on menubar<sup>[1]</sup>
- [ ] Structure submenu according to outline indicated above.
- [ ] Separate Texture Path settings out into its own Settings submenu<sup>[2]</sup>
- [ ] Separate Render, Export, Region, Startup out into their own submenus<sup>[3]</sup>

[1] Find a more appropriate location to put settings menu option as its both hard to find and the setting options do not necessarily correspond to "Render".
[2] Users also have difficulty locating Texture path detection/setup because its hidden in here too.
[3] These submenus under Settings can just be a shortcut to the respective tab in one large settings widget.  That way to get between settings categories you don't need to close one window and go back into Settings > [Menu you're trying to switch to].  Putting each of these in a visible dropdown menu will make them more user accessible.
#### Related Issues
#25 Render Settings & View enhancements
#### Tracking

Refactor Progress #32

**Comment by hexabits** [comment]
This entire issue is severely outdated in terms of plans and progress.  I will attempt to rewrite the issue before closing it just for posterity.

**Comment by neomonkeus** [comment]
:+1:
