### ISSUE TITLE
Collision display enhancements

### ISSUE THREAD

**Issue by hexabits** [niftools/nifskope#14]
### Tasks
- [ ] Display toggle shortcut (H)
- [ ] Display cycles through OFF, WIRE, SOLID+WIRE
- [x] Fix display of CVS
#### Add keyboard shortcut

Many of the features should be given keyboard shortcuts.  We should either include the shortcuts with each feature improvement, or save them for all at once.
#### Add new display mode (SOLID+WIRE)

The collision currently only displays as a wire.  For complex shapes this does not give you a good idea of the "coverage", or how accurately it fits the shape.  A new mode should be added which fills in the surfaces so that the faces can be seen.
#### Improve ConvexVerticesShape implementation

The convex hull algorithm uses a naive algorithm.  It does not generate an actual convex hull. It instead draws an edge between every combination of vertices.

**Comment by hexabits** [comment]
#### Example of FILL + LINE:

![fill line](https://f.cloud.github.com/assets/170077/1584544/e7ff8f76-520d-11e3-8283-1559e048b296.jpg)

As you can see, it helps you see the actual space the collision takes up.

#### Examples of poor CVS display in NifSkope, versus the fix:

![comparison](https://f.cloud.github.com/assets/170077/1584546/f94993d0-520d-11e3-919d-9347aa0abffd.jpg)
![comparisonmemoized](https://f.cloud.github.com/assets/170077/1584547/fcd8e168-520d-11e3-95b5-78ecde39fbcf.jpg)

Figure 1 is ~180 vertices, Figure 2 is ~210.  However, Fig 1 is made up of 2 shapes of ~105 and ~75 verts.  With my brute force algorithm this is much faster than Fig 2, which is 1 shape of ~210.

So, I developed a memoization for each shape so that the convex hull is not being recomputed each draw.  There are also small issues with my technique, like coplanar vertices still draw edges between each other.  This is because all the triangle combos between these verts are also coplanar, and thus fail a plane test.  This is still much better than the original.

At ~210 vertices the program does stall for a few seconds while loading the mesh, as it generates the convex hull.  Honestly, no one CVS should be 210 vertices.  It's kind of ridiculous, and collision that high-vert should just be redone.
