### ISSUE TITLE
Header Strings enhancements

### ISSUE THREAD

**Issue by hexabits** [niftools/nifskope#18]
Block names are stored in the header and referenced by index.  This reference gets muddled when copy/pasting blocks into new NIFs.  It does not bring the actual strings over with it, but references the string at the same index.

It may be possible to reconcile differences between the string indices by adding all the strings which are needed by the block/branch to the end of the strings and modifying the pasted blocks' indices to point to the new location.

However such repeated actions over time could cause a lot of header string cruft.  Might be worth looking into to make a Spell which removes unused strings.
## Task List
- [x] Source -> Destination header string reconciliation and integration.
- [x] Spell which removes unused Strings.
- [x] ~~Allow reorganization of Strings.~~ Deferred for new dedicated ticket
- [x] ~~Improve method of reassigning Strings (Clicking the "TXT" button is a little obscure)~~ Deferred for new dedicated ticket (same ticket as above item)

**Comment by neomonkeus** [comment]
You're reading my mind, just finished up helping a user with this issue about 10 minutes ago. Was thinking about a way to auto-resolve this. Could add an verification step when this attribute is updated, much in the same way array lists resize, running through blocks to check if there are missing or redundant strings

**Comment by L0FKA** [comment]
Then I will track this one ._.

**Comment by hexabits** [comment]
@L0FKA  Sorry.  Did not mean to offend. :)

I had mentioned it in this ticket, and decided to rename and reorganize this ticket today to include several other issues as well. 

Please submit anything you can think of, bugs, feature requests.  I couldn't understand exactly the last part of your ticket (reverse animation), but feel free to submit it as a separate ticket.  If you do create issues try to include only related issues in one ticket.  The animation request and header strings issue weren't really related.

Thank you for contributing.

**Comment by hexabits** [comment]
I'm refraining from creating a ticket for this, because I am unsure of the direction editing header strings is going to take, but I will post this here for now:

I noticed that when I click on "TXT" I get the index for the header string, and the spinbox to cycle through the numbers.  It allows you to enter a number > the number of actual strings for one.  This acts the same as entering the last header string index.  Meaning if you enter "50" and there are 3 strings, it acts as if you entered 3.

Also, when you click away from the field, the number remains, and the spinbox remains.  Meaning it doesn't "complete" the edit.   To complete the edit you must click back inside the field and hit Enter.

So, these are technically bugs, but they may be resolved with whatever changes we make anyway.

**Comment by neomonkeus** [comment]
Two possible options, 
1. Allow direct editing of the text, creating a new string if one does not already exist and if one does using that block number.
2. Dropdown selection of Strings from header.
3. Both.

I agree the above should warn the user upon entering values which are not valid.
Also I know some nif's define max string length, but not sure if that value is updated should a new string of len() > max be defined.
