### ISSUE TITLE
LOD Slider for BSLODTriShape visualization

### ISSUE THREAD

**Issue by hexabits** [niftools/nifskope#22]
Info: http://niftools.sourceforge.net/forum/viewtopic.php?f=4&t=3363&start=0#p23326
### Task List
- [x] UI/widget for manipulating LOD Level
- [x] Show triangles for LOD Level set in widget. 2 = {0, 1, 2} (all visible), 1 = {0, 1}
- [x] Hide/Disable slider for meshes without BSLODTriShapes
- [ ] Usability improvements to current implementation

**Comment by hexabits** [comment]
Implementation is currently a bit rudimentary...  can improve the UI, but the underlying logic seems sound and shouldn't need changing.

Example:

meshes/architecture/whiterun/wrbuildings/wrjorvaskr01.nif

Level 1
![level1](https://cloud.githubusercontent.com/assets/170077/2966032/7ea24c18-db05-11e3-82f7-09bb9f7676ef.jpg)
Level 2 (Everything visible)
![level2](https://cloud.githubusercontent.com/assets/170077/2966033/7ea50f52-db05-11e3-9b68-ffdd248e510b.jpg)

(There is no difference between Level 0 and Level 1 on this mesh)

Slider position is saved with other app settings and thus is maintained across sessions.  Given the sparse UI currently, this may lead to confusion.  Maybe it should always default to 2...

**Comment by hexabits** [comment]
Updated tasks to include:
- Hide slider for meshes without BSLODTriShapes

It will be a small amount of work to do so.  Alternative being to at least show it for just the appropriate user versions.

**Comment by hexabits** [comment]
Current Issue:  I originally implemented the enable/disable for the slider with signals but it required editing `NifModel` and I thought this was ugly and trashed it.  I thought my current solution using `qApp->allWidgets()` was functionally equivalent,  but in actuality this is enabling/disabling all widgets named 'tLOD' across all windows based on the last mesh loaded.
