### ISSUE TITLE
NifSkope.pro file cleanup

### ISSUE THREAD

**Issue by hexabits** [niftools/nifskope#27]
NifSkope.pro should be reorganized and restructured to better operate between platforms, individual machines, and compilers.  Dependency management should be improved.
### Issues.
1. There is an incompatibility with the `NIFSKOPE_VERSION` and `NIFSKOPE_REVISION` macros between Qt Creator and VS 2010-2012.  Also, VCPROJ files do not get generated optimally in addition to this macro formatting error.  Visual Studio should be somehow targeted directly.  (See Below)  
2. The following defines should be looked into:
   - `USE_GL_QPAINTER`
   - `EDIT_ON_ACTIVATE` (alt: `Q_OS_WIN`)
   - `NO_MESSAGEHANDLER` (alt: `QT_NO_DEBUG`)
   
   I would prefer to allow stats rendering on all builds, so `USE_GL_QPAINTER` could be done away with.  Also, `EDIT_ON_ACTIVATE` may be a relic that is not even needed anymore.  
   ---
### Goals
1. Use QT_INSTALL_BINS to find and copy DLLs to build folder _when dynamic_.  Ignore when static.
2. Copy shaders, lang folders to build dir.  
   - Look at INSTALLS option  
   - Alternatively copy to PWD_OUT with QMAKE_POST_LINK  
3. Create make targets for NSIS, docsys, doxygen, etc.
4. Clean up the build dir significantly using UI_DIR, MOC_DIR, OBJ_DIR, RCC_DIR to put them in appropriate subdirs.
5. Differentiate between MSVC builds by Visual Studio and those by Qt Creator.  Checking for `*msvc*` scope does not do this alone, though one can test if the build is a "shadow build".   Qt Creator builds outside of the project root by default.  Visual Studio does not.
6. Setting up 32-bit / 64-bit compiler scopes should be looked into.  Qt precompiled libraries come in 32 and 64-bit.  However, static compilation should be an option for Qt, and we should build our own 32- and 64-bit Qt libs to link against.
7. Consider putting flags in place to enable C++0x / C++11 support for the compilers that can use it.  Like 32/64bit code this would be just put in with the off chance that the source will utilize such features in the future.  There are quite a few nice things about C++11 so it might eventually sneak into the codebase.  
   
   See:
   - http://qt-project.org/doc/qt-5/qmake-advanced-usage.html
   - http://paulf.free.fr/undocumented_qmake.html
   - https://stackoverflow.com/questions/3984104/qmake-how-to-copy-a-file-to-the-output
     ---
#### Task List
- [x] Clean up defines.  
- [x] Make targets for docsys, doxygen, ~~NSIS~~ (Create its own ticket).  
- [x] Split dependencies into their own config blocks.  
- [x] Copy necessary files and folders to build directory.  
- [x] Deal with static vs dynamic builds, e.g. copying DLLs to build dir.  
- [x] Reorganize compiler/platform scopes.  (Only minor work, later work needed)
#### Deferred Tasks (Will make future ticket)
- ~~Solve macro incompatibilities between Visual Studio and Qt Creator _et al._~~ Seems to have fixed itself?  
- ~~Add Visual Studio specific code so that VC++ project files are created correctly.~~ Seems to have fixed itself?  
- Lay groundwork for future 32-bit / 64-bit specific builds, flags for C++0x/C++11 support.  
#### Tracking

Refactor Progress #32 

---

I have to edit the source to get rid of the ridiculous macro incompatibility.

```
#define VERSION QString(NIFSKOPE_VERSION).replace("\"", "")
#define REVISION QString(NIFSKOPE_REVISION).replace("\"", "")
```

I add an additional set of quotes so that VS2010+ stops erroring during compile.  I then run it through this macro so that the strings come out the same no matter what platform it's built on.

**Comment by hexabits** [comment]
### Latest Revisions

[NifSkope.pro](https://github.com/jonwd7/nifskope/blob/qt5/restructure/NifSkope.pro)
[NifSkope_functions.pri](https://github.com/jonwd7/nifskope/blob/qt5/restructure/NifSkope_functions.pri)
[NifSkope_targets.pri](https://github.com/jonwd7/nifskope/blob/qt5/restructure/NifSkope_targets.pri)

### Commits

Initial .pro/.pri config modifications jonwd7/nifskope@017af40954a2bfbb231943ab16c47168aeed7513
Minor .pro/.pri cleanup jonwd7/nifskope@a0c1b564a96e040dc585ede424f5437e52d701cb
Better sed support for Windows jonwd7/nifskope@dc31ac256291a32faae1f807df955932e51df4b2
More robust multi-platform file copying jonwd7/nifskope@20ba5fec470b804b66b73892f76b9b0ed1a67f4c

**Comment by hexabits** [comment]
While working on qt5/restructure, I am cleaning up the NifSkope.pro file.

Here is my current progress:  https://gist.github.com/jonwd7/9348265

I currently:
1. Clean up the build dir significantly using `UI_DIR`, `MOC_DIR`, `OBJ_DIR`, `RCC_DIR` to put them in appropriate subdirs.
2. Copy the appropriate Qt DLLs, the shaders and lang folders, and the XMLs to the build dir.  DLLs only when the build is not static.
3. Cleaned up the compiler scopes slightly.

I still need to:
1. Flesh out the compiler scopes. Being explicit with compiler flags is best. 
2. Possibly do build subdirs for x86/amd64, and/or build to a subdir for each Git revision.  Meaning, you can make a commit, build it, and it will not overwrite builds from previous commits.  A way of keeping a build history for comparison.
3. If I can successfully target VS2010/2012 and differentiate it from Qt Creator, the macro fix above may not be necessary.

---

One thing I'm kind of annoyed with is how cleaning up the project directories has made the actual organization of the IDEs worse...  That is, the Headers and Source trees are no longer flat,  but say  Headers > src and Source > src ...  Which is redundant and also annoying to have to expand another level to get to the source files.  It's a one-time issue though, as they are only collapse when you open the project.

**Comment by neomonkeus** [comment]
Do we need to update the nif.xml & kmf.xml sub-modules repositories. 
git --submodule update will pull the latest but need to check if the docsys .gitmodules point to gihub or sf.net repos. 

Edit: Checked there. They point to the old sf.net versions so that needs to be updated, or at the very least synch'd.

**Comment by hexabits** [comment]
```
[submodule "docsys"]
    path = docsys
    url = git://niftools.git.sourceforge.net/gitroot/niftools/nifdocsys
[submodule "qhull"]
    path = lib/qhull
    url = git://gitorious.org/qhull/qhull.git
```

The lib/qhull is because I moved qhull.  It's just qhull in the official branch.

**Comment by neomonkeus** [comment]
Yeah I checked the .gitmodules in the sf.net docsys and they point to the sf.net versions. They are out of date. Qhull is fine as its external.

**Comment by hexabits** [comment]
OK, I've split off some things into a PRI file (project include).  Here is the current setup:  

[NifSkope.pro](https://gist.github.com/jonwd7/9348265)
[NifSkope_functions.pri](https://gist.github.com/jonwd7/9350674)

I did this to de-clutter the main .pro file.  I could even split a few other things into PRI files.   I may also move the version/revision macros to the PRI file.

**Comment by hexabits** [comment]
I've updated the files:

[NifSkope.pro](https://gist.github.com/jonwd7/9348265)
[NifSkope_functions.pri](https://gist.github.com/jonwd7/9350674)

In `QMAKE_PRE_LINK` I use `sed` to grab `build\README.md.in`, and replace the `@VERSION@` string with the version stored in `build\VERSION`.  I then output it to `.\README.md`.  For Windows, it looks for GnuWin32's `sed`.  It doesn't do anything if it's not there.  I would like to query for the `sed` command and see if it exists on the path, but I'm not positive there is a foolproof way to do this.  The `system()` function which is supposed to help with this seems unreliable.  For linux it just assumes `sed` is a valid command on the path.

In `QMAKE_POST_LINK` I then copy all the .md (Markdown text, from the repo) files from the project root and rename them to .txt and put them in the build directory.

I also now copy the style.qss file and qhull/COPYING.txt to the build dir. 

Basically the build directory now looks exactly like the official release, with the exception of the docs folder.

Regarding that, I have some targets to make.  In the .pro file you can define extra targets which you can then run make commands for them.   So I can create a `docs` target which runs nifxml_doc.py and installs the docs to the build directory.  ~~It'd be simply `make docs` or `make -f Makefile.Release docs` depending on if I can get rid of the separate debug/release targets which happen because we use the options `debug_and_release` and `debug_and_release_target`.  I may be able to work around it, but I'm not sure yet.~~

Also, not relevant to the release package / installer, I can make a doxygen target which builds the NifSkope API docs.  What I found out about Doxygen is that it can also build a QCH (Qt Compressed Help) file so that the NifSkope docs can be loaded directly inside of Qt Creator.  Updating the QCH file requires Qt Creator to be closed I believe, or it won't update.   I'm not 100% certain on that, and it may just not show the updated files until a restart, but the file does get written correctly.

So, I can make a Doxygen target for both the normal online docs and the docs for Qt Creator.

---

I guess an alias of `jom -f Makefile.Release docs` is just `jom release-docs`.  So that's more than simple enough.

**Comment by hexabits** [comment]
OK, docsys target was pretty easy I must say.  Here is the current state of the targets PRI file:

[NifSkope_targets.pri](https://gist.github.com/jonwd7/9397092)

I generate the HTML files, move them to the build dir, copy the CSS/ICO file, and then clean up the .pyc file so that the submodule doesn't get marked dirty.

**Comment by neomonkeus** [comment]
would it make it easier just to add .pyc to the .gitignore?

**Comment by hexabits** [comment]
I thought that, but it doesn't work.  You're still adding a file to a submodule and git considers that dirty.  It could work if it's added to the docsys .gitignore.  Maybe.

**Comment by hexabits** [comment]
The latest versions can now be seen from here:

[NifSkope.pro](https://github.com/jonwd7/nifskope/blob/qt5/restructure/NifSkope.pro)
[NifSkope_functions.pri](https://github.com/jonwd7/nifskope/blob/qt5/restructure/NifSkope_functions.pri)
[NifSkope_targets.pri](https://github.com/jonwd7/nifskope/blob/qt5/restructure/NifSkope_targets.pri)

The commits:

Initial .pro/.pri config modifications jonwd7/nifskope@017af40954a2bfbb231943ab16c47168aeed7513
Minor .pro/.pri cleanup jonwd7/nifskope@a0c1b564a96e040dc585ede424f5437e52d701cb
Better sed support for Windows jonwd7/nifskope@dc31ac256291a32faae1f807df955932e51df4b2
More robust multi-platform file copying jonwd7/nifskope@20ba5fec470b804b66b73892f76b9b0ed1a67f4c
