### ISSUE TITLE
Skyrim Material: Int values not mapping to enums

### ISSUE THREAD

**Issue by neomonkeus** [niftools/nifskope#42]
The **Skyrim Material** on `bhkMoppBvTreeShape` is not being populated correctly on load.  It has a value of 0.  When selecting a new value, the enum mapping remains (it says SKY_HAV_...) and persists even after things like Reset Block Details.

Additionally, the **Skyrim Material** on the sub-block `bhkCompressedMeshShape` does not show the enum mapping, but the integer.  When double-clicking to activate the edit box and clicking away, it resets this value to 0.

Also, when double clicking, the box is completely blank (why it likely resets to 0), until you click on the dropdown arrow to the right.  If an Enum value is correctly displayed in the field, double clicking to edit will show the right index in the drop down (the current enum).

<u>**Examples:**</u> 
    ~\meshes\architecture\orclonghouse\orcawning01.nif
    ~\meshes\architecture\farmhouse\farmhouse01.nif  
### Task List
- [x] ~~Fix **Skyrim Material** on `bhkMoppBvTreeShape` blanking to 0 on NIF load.~~ _`INVALID`_
- [x] ~~Fix integer to enum mapping on `bhkCompressedMeshShape`.~~ _`INVALID`_
- [x] Assure that even when an integer value is entered, it maps to the enum value on edit completion. _`CONFIRMED`_

**Comment by hexabits** [comment]
I forget if we mentioned it, but is this due to the recent nif.xml release?  Specifically the lack of mapping to the enum types.   That NIF could just be wrong for all I know.  I'll look into it.

OK, looked into it more.  It may not be related to niftools/nifxml#19.   I went back pretty far past a lot of the nif.xml changes and the value is still 0 and the enums do not map.

**Comment by neomonkeus** [comment]
I opened an issue on nifxml for the `bhkCompressedMeshShape` skyrim_material value `401067200` as there is no enum value to map to - https://github.com/niftools/nifxml/issues/20

**Comment by hexabits** [comment]
Cross referencing niftools/nifxml#21 ... `bhkCompressedMeshShape` is apparently not an issue and neither is `bhkMoppBvTreeShape`.

**Comment by hexabits** [comment]
Closing.  Resolved by niftools/nifxml#21 the issue is integral to nif.xml, not NifSkope.
