### ISSUE TITLE
Tooltips: General Usability Issues

### ISSUE THREAD

**Issue by hexabits** [niftools/nifskope#47]
Large tooltips like enum type descriptions can take a long time to load, and they are computed continuously as you hover.  Take for example the Havok collision layers or materials.  In the Type column, hover over the enum type and it will take a long time to load, and it never loads the same way twice.  It's pretty much impossible to read and if it loads well, it might still disappear before you can even read it.  I've already refactored the method some to deal with it, but it's not helping, as the sluggishness seems to stem from the UI having to parse such a large HTML table.  The method is `QString NifValue::typeDescription( const QString & typId )` in **nifvalue.cpp**

I propose a few options:
1. A dedicated widget (like Inspector view) which displays the descriptions for highlighted cells.
2. A button on the cell which opens a modal window with the description.

We could then keep the problematic descriptions from popping up in a tooltip and to view the descriptions you need to use another method.

---
#### Secondary Issues

Enum type descriptions are unordered too, because they are stored in a QHash.
## Task List
- [ ] Attempt to make tooltips more "stable" by improving their display/hide time or changing how they are toggled.
- [ ] Consider moving certain tooltips to a widget or modal to improve usability.
- [ ] Fix formatting issues with various descriptions.
- [x] Fix sorting issues with enum type descriptions and any others.

**Comment by neomonkeus** [comment]
I had made a proposal to update the nif.xml structure to add a <shortdescription> & <longdescription> attributes for cases like enum where there is alot of information present. It is also generally aimed at ensuring the quality of information within the nif.xml and seeing what is missing information. Would this help in that case as you could display the short description with an option to pull the more detailed version if needed, or is it just the same thing and would end up hiding information from the use.

**Comment by hexabits** [comment]
Fixed the ordering problem in jonwd7/nifskope@52f2f20234de29ebf75b98db50db801ba5bc4ca5

**Comment by neomonkeus** [comment]
With the port to Qt5, the font size seems smaller than before as reported by Hanaisse and verified.
Think we should we add an option to increase size for accessibility reasons, either specifically for this or global options.

**Comment by hexabits** [comment]
It was an intentional change.  The default was just too large.  It was the only way to get large enums to fit.  With that said I agree it's quite small, but tooltips are next to useless as currently implemented. 

One can edit the QSS file in their install directory:

``` CSS
QToolTip
{
    opacity: 223;
    color: steelblue;
    border: 1px solid steelblue;
    border-radius: 5px;
    padding: 4px;
    background: ghostwhite;
    font-size: 10px;
}
```

... You just remove or change the font-size.

There is no way that I know of off the top of my head to make it an actual in-app option.

---

I think showing the help text in a status bar at the bottom of the window might be a good idea.
