### ISSUE TITLE
OpenGL Refactoring

### ISSUE THREAD

**Issue by hexabits** [niftools/nifskope#56]
Catch-all ticket for OpenGL / rendering changes.
## Task List
- [X] ~~Code cleanup~~ _Deferred_
  - [X] ~~Scene Refactor (#79)~~ _Deferred_
  - [X] ~~Camera Refactor~~ _Deferred_
- [x] Multisampling
- [x] Anisotropic Filtering
- [x] Decal / alpha z-fighting with solid surfaces  (See: [glPolygonOffset](http://joglblogl.blogspot.com/2007/01/blending-with-glpolygonoffset.html), [Polygon Offset](http://www.felixgers.de/teaching/jogl/polygonOffset.html))
- [x] Mesh selection with Z-fighting geometry incorrect when Settings > Antialiasing enabled (#57)
- [X] ~~Update existing shaders for Fallout (#26)~~ _Deferred_
- [x] ~~Update existing shaders for Skyrim (#26)~~ Replaced w/ all new shaders.
- [x] Improve the Save View to File widget (#60)
- [x] New shaders for Skyrim (See below)
- [x] Animation controllers for Skyrim's shader property blocks.
## Ideas / Future Plans _`WIP`_
- `DONE` ~~Rewrite the current shader loading programs.  It's very esoteric and I'm not sure I can pass along vital information to the shaders from blocks like `BSLightingShaderProperty`, `BSEffectShaderProperty`, or `BSShaderTextureSet` such as:~~
  - Emissive color (BSLSP)
  - Emissive multiple (BSLSP)
  - Glossiness (BSLSP)
  - Specular Color (BSLSP)
  - Specular Strength (BSLSP)
  - Source Texture (BSESP)
  - Greyscale Texture (BSESP)
- `DONE` ~~With such a rewrite, I could expose information to the shaders which would allow for much greater rendering accuracy.  Examples include:~~
  - Environment mapping
  - Proper specular roughness / power / color
  - Proper emissive color and emissive multiple
  - Applying the gradient textures to alpha effects (BSEffectShaderProperty) which affects the color and falloff (e.g. the glowing parts of Daedric armor or almost any magic effect)
  - Proper UV offsets, scale, animated UVs.~~
- Strip out any fixed function entirely.
- Rely more heavily on Qt's OpenGL functions which would greatly decrease raw OpenGL code, repetitive code, and allow for easier implementation of things like the shader loading rewrite.
### Related
#26 Investigate fixed-function vs shader pipeline
### Tracking
#32 Refactor Progress

**Comment by hexabits** [comment]
## Progress Update

### Multisampling AA and Anisotropic Filtering

Code was in place to handle this but not correctly implemented.

[Gallery](http://imgur.com/a/WxZwt)

### Shader support for Skyrim, Fallout

Under certain conditions (mesh, lighting/shader property values) NifSkope would load shaders for NIFs which displayed normal mapping and glow mapping.  These were never updated for Fallout and Skyrim.

[Example (Skyrim)](http://imgur.com/a/WxZwt#2vPLtcL)
[Example (Fallout 3)](http://imgur.com/a/WxZwt#KInFxOQ)

There are still many issues when it comes to rendering accuracy, biggest issue being specular (it's completely wrong). 

### Alpha depth biasing

Decals / alpha in the same plane as the base geometry would z-fight (flicker). 

#### [Comparison Gallery](http://imgur.com/a/PdD1F)

#### Youtube Video

<a href="https://www.youtube.com/watch?v=o5KWo6Uxlks" target="_blank"><img src="http://img.youtube.com/vi/o5KWo6Uxlks/0.jpg" alt="IMAGE ALT TEXT HERE" width="240" height="180" border="10" /></a>

---

The total sum of all these changes makes for a marked contrast in rendering quality:

##### No AA, No AF, No Shaders, Decal Z-fighting

![before](https://cloud.githubusercontent.com/assets/170077/3107439/2ee6aec2-e685-11e3-95da-5c4a24b0e0b2.png)

##### AA, AF, Shaders, No Decal Z-fighting

![after2](https://cloud.githubusercontent.com/assets/170077/3108682/1071c66c-e693-11e3-98b4-b0aefc37b2ab.png)

**Comment by hexabits** [comment]
This ticket has run its course as I am now focused on creating a new renderer from scratch.  The old renderer will stay in place as a fallback but will probably be deprecated. 

I will be opening a new meta ticket to track the plans for the new renderer.
