### ISSUE TITLE
"Save View to File..." Enhancements

### ISSUE THREAD

**Issue by ttl269** [niftools/nifskope#60]
_Outline - @jonwd7_

---

The existing (but disabled) "Save View to File..." action is bit confusing for the user.
## Tasks
- [x] Choice of using the screenshots directory in your NifSkope folder (it auto-creates the directory if it's not yet present).
- [x] Choice of saving to the same folder as the NIF file.
  - (You can still save anywhere by opening the File dialog)
- [x] Create a default filename based on the NIF filename and the datetime. 
- [x] Save your preferred JPEG quality.
- [x] Change the file priority to JPG > PNG > BMP.  So that JPG is the default.
- [x] Widen the dialog for legibility. 
- [x] Show a warning message if the file cannot be saved, e.g. the path or file extension are not valid.
- [x] Set window title
## \- [x] Rename "OK" to "Save".

_Original Post by @ttl269_

> Selecting JPEG format when saving a screenshot produces no file (NifSkope 1.2.0a1.dev19).
> I think that line with filepath should not be editable but only viewable (as for example in CK) and only way how to specify the file (and image format) should be via standard filerequester - clicking on "File" button. Editable filepath is little confusing because user can write there any filename (with or without extension) and don't know which image format will (and could be) be used. Providing filename without extension produces no file.
> Also some error message should appear in case that nothing was saved.

**Comment by hexabits** [comment]
> Selecting JPEG format when saving a screenshot produces no file (NifSkope 1.2.0a1.dev19).

Already fixed.  It wasn't the code, just the imageformats folder (DLLs) was missing from release zips. See: #58 

I wasn't going to create a ticket for the enhancement part, but since you made one, I will end up utilizing your post to show the progress and have a task list if you don't mind.

Currently:

![ipt18tw](https://cloud.githubusercontent.com/assets/170077/3141057/74fef6c8-e962-11e3-9af6-d46d41f09d8b.png)
![pxcnecb](https://cloud.githubusercontent.com/assets/170077/3141058/768b14b8-e962-11e3-805a-8fd57f71fb92.png)

---

P.S. I share your qualms with the FileSelector widget (the File line) and it's an issue in general, with anywhere it is being used.  So improvements to FileSelector will be discussed in other tickets.

**Comment by hexabits** [comment]
### Deferred Tasks
- Save your preferred / last-used file extension, i.e. if you selected PNG last it will default to PNG.
- Automated cropping based on empty space around NIF ("Crop & Save").  Alternative:  Manual cropping in a widget.
- Eventually relocate to File menu.  However, this relies on the UI restructuring to happen first.

---

Will create a new ticket for these, and the File menu one will probably just end up in the general UI separation / restructure tickets.
