### ISSUE TITLE
Scene refactoring

### ISSUE THREAD

**Issue by hexabits** [niftools/nifskope#79]
The Node class is currently very oddly laid out.  It handles a number of functions which are better served as subclasses, such as drawing of Havok and furniture.  It is also a non-abstract class from which a number of other Scene objects inherit such as Mesh.

The issue is that the Node class is meant to be analogous to `NiNode` (niobject).  The Mesh class is meant to be analogous to `NiGeometry`.

Thus it stands to reason that Mesh should not inherit from Node and instead they should share an abstract parent which is analogous to `NiAVObject`, since `NiGeometry` and `NiNode` both inherit from it.

However, markers and Havok collision type blocks do not inherit from `NiAVObject` in the NIF structure, so the drawing logic should not be part of the `NiAVObject` analog class, but instead an `IDrawable` interface.  Collision and furniture (etc.) markers do not have any parent in common, as markers are actually treated as `NiExtraData`... and collision's inheritance tree consists of `bhk*` objects such as `bhkShape`.

So, how closely to mirror the NIF format is up for debate.  It can be mirrored perfectly, and if something needs to draw to the Scene, it can use `IDrawable`, or a more generic `Shape` class can be an abstract parent for Mesh, Collision, and Markers and the `IDrawable` interface idea can be done away with.

Also, the `Controllable` class is more or less meant to be an interface, so it should be renamed to reflect this, as well as be made abstract.
### Task List
- [x] Refactor Controllable to IControllable 
  - [x] Rename glcontrolable.h to icontrollable.h
  - [x] Make IControllable abstract
- [ ] Refactor Node > Mesh (et al.) inheritance
- [ ] Remove furniture and Havok drawing from Node, create dedicated classes for drawing these.
- [ ] Create `NiAVObject` analog, reparent Mesh, Node, etc. under this new abstract base class.
- [ ] Create `IDrawable` interface for objects which must have a `::draw()` function.
### Tracking
#56 OpenGL Refactoring

**Comment by hexabits** [comment]
@neomonkeus  @ttl269

I believe I have decided to attempt recreating the renderer from (mostly) scratch.  Basically, I can hardly understand what to do and where since I did not write the code myself, which impedes my ability to add in new features. 

Now that Qt 5.5 is out I have access to the developmental release of Qt3D, their overhauled 3D library.  If I create the renderer using _modern_ OpenGL I will be in a much better position to implement the things I would like to, like modeling modes, transform gizmos, screenspace effects (like refraction), and so forth.

Some links:

http://doc.qt.io/qt-5/qt3d-index.html
http://doc.qt.io/qt-5/qt3d-overview.html
http://doc.qt.io/qt-5/qt3d-examples.html

Note:  I will NOT be using the QML API for Qt3D because I kind of despise QML.  :)

---

I will be keeping the old renderer fully intact, and fully switchable should anyone need to use the old renderer.

**Comment by neomonkeus** [comment]
Yeah go for it.

**Comment by hexabits** [comment]
I've decided that Qt3D simply isn't up to the task yet.  As of 5.5 it's only a "technical preview" and as such is API-incomplete and the documentation is pretty non-existent.

I think I will just roll my own using the existing QOpenGL\* classes when possible, and my own raw OpenGL 3.x/4.x otherwise.

I've decided that I need to just redo the scene management entirely, redo the renderer entirely, and so basically anything related to the viewport is going to get rewritten.

So, I may either close this issue or adapt it to track just the Scene/Scenegraph refactoring.  I will have to redo the OpenGL meta ticket, or close that one and open a new one also.
